openapi: 3.0.3
info:
  title: Face Recognition API For Choreo
  description: >-
    This is a Face Recognition API For Choreo written in Python
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:5000
tags:
  - name: face
    description: Face Recognition API
paths:
  /recognize:
    post:
      tags:
        - face
      summary: Face Recognition based on source image and target image
      description: Matches if the source image is similar to the target image
      responses:
        "200":
          description: Valid Face Recognized
        "404":
          description: Face not recognized
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payload"    
components:
  schemas:
    payload:
      type: object
      properties:
        target:
          type: string
          example: "BASE64 IMAGE"
        source:
          type: string
          example: "BASE64 IMAGE"
